services:
    americor_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

###> doctrine/doctrine-bundle ###
    postgres:
      image: postgres:${POSTGRES_VERSION:-16}-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-dev}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
        POSTGRES_USER: ${POSTGRES_USER:-dev}
      volumes:
        - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
